### ISSUE TITLE
SQS support

### ISSUE THREAD

**Issue by sam-goodwin** [sam-goodwin/itty-aws#1]

**Comment by garysassano** [comment]
>- ✅ Any modern API using plain JSON protocol should work out of the box.

Does [this](https://aws.amazon.com/about-aws/whats-new/2023/11/amazon-sqs-support-json-protocol/) mean that SQS is also supported as of SDK [v3.447.0](https://github.com/aws/aws-sdk-js-v3/releases/tag/v3.447.0)?

**Comment by sam-goodwin** [comment]
Oh good point! I'll have to test this out.

If this trend continues, all of AWS SDK could fit in a few KB.
