### ISSUE TITLE
Advantages over using bundled AWS-SDK v3 for Node.js 18 runtime

### ISSUE THREAD

**Issue by PatrykMilewski** [sam-goodwin/itty-aws#17]
Hey, I was reading the readme and I have one question:

> Bundle size and cold start times degrades as a piece of code uses more AWS APIs

Is this really true, since aws-sdk v3 is present in the Lambda runtime anyways starting from Node.js 18? (source: https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html) It's the same as it was for aws-sdk v2 for older runtime version

This argument about bundle size would still make sense, if this lib would be available for Node.js 16 and older runtimes, but there is hard requirement for Node.js 18 due to fetch lib

**Comment by sam-goodwin** [comment]
Surprisingly, it is true. Even when relying on the AWS SDK v3 bundled into the Node 18 Lambda Runtime, importing it is slower bundling it in with ESBuild and paying the cost of downloading the bundle. It's wild. Not sure what AWS is doing there.

I've got a very basic benchmark that shows that, even when just making a single PutItem call with DynamoDB, itty-aws is usually ~100ms (often times more) faster than bundled/un-bundled AWS SDK v3 on Node18. See: https://github.com/sam-goodwin/itty-aws/tree/main/benchmark/functions/src

Take a look at this thread: https://twitter.com/sussmansa/status/1593804631192346624?s=20&t=sCzgVrhH_J8qhDlXhMoYKg. It's a known problem. Not sure if AWS will solve any time soon.

> This argument about bundle size would still make sense, if this lib would be available for Node.js 16 and older runtimes, but there is hard requirement for Node.js 18 due to fetch lib

Agree that the requirement on Node 18 is a problem. I've been thinking of making it work for more environments: https://github.com/sam-goodwin/itty-aws/issues/13

**Comment by PatrykMilewski** [comment]
Thank you for clarifying that! 

Lib looks really promising and at the same time it's a huge disappointment that AWS can't do similar optimisations in oder to keep aws-sdk smaller and faster
