### ISSUE TITLE
S3 support

### ISSUE THREAD

**Issue by sam-goodwin** [sam-goodwin/itty-aws#3]

**Comment by naorpeled** [comment]
Hey @sam-goodwin,
first of all, awesome initiative!!!

May I be assigned to this task?

**Comment by sam-goodwin** [comment]
Go get it! Thanks for taking the initiative ❤️. My tests kind of suck - hit me up if you need help figuring that out. It depends on some resources I hand deployed to my own account lol.

**Comment by sam-goodwin** [comment]
What's your plan for xml? I was looking at https://www.npmjs.com/package/fast-xml-parser which might add 20-30 KB.

**Comment by naorpeled** [comment]
> What's your plan for xml? I was looking at [npmjs.com/package/fast-xml-parser](https://www.npmjs.com/package/fast-xml-parser) which might add 20-30 KB.

Hmm, what do we need XML for?
(I hope it's not a stupid question 😅)

**Comment by sam-goodwin** [comment]
I updated the way tests work so that they are not tied to my environment - https://github.com/sam-goodwin/itty-aws/pull/12

I also added a CONTRIBUTING.md guide to help with setting up an environment https://github.com/sam-goodwin/itty-aws/blob/main/CONTRIBUTING.md
